=== lsm1987/DataExporter/docs/sample/schema/SampleComplex.table.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "SampleComplex.table.json",
    "title": "SampleComplex",
    
    "type": "array",
    "items": {
        "description": "복합 샘플 테이블 항목",
        "type": "object",
        "properties": {
            "id": { "description": "ID", "type": "string" },
            "name": { "description": "스테이지명", "type": "string" },
            "openTimes": {
                "description": "개방 시간",
                "type": "array",
                "items": { "$ref": "Struct.schema.json#/definitions/ContentsOpenTime" }
            },
            "rewards": {
                "description": "보상 아이템 목록",
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "itemId": { "description": "아이템 ID", "type": "integer" },
                        "count": { "description": "아이템 수량", "type": "integer" },
                        "condition": {
                            "description": "보상 획득 조건",
                            "type": "object",
                            "properties": {
                                "firstClear": { "description": "최초 클리어", "type": "boolean" },
                                "timeLimit": { "description": "클리어 시간 제한. 단위: 초", "type": "integer" }
                            }
                        },
                        "messages": {
                            "description": "보상 획득 시 메시지 목록",
                            "type": "array",
                            "items": {
                                "description": "보상 획득 시 메시지",
                                "type": "object",
                                "properties": {
                                    "text": { "description": "메시지", "type": "string" },
                                    "delay": { "description": "메시지 등장 딜레이. 단위: 초", "type": "number" }
                                }
                            }
                        }
                    }
                }
            },
            "exp": {
                "type": "object",
                "properties": {
                    "accountExp": { "description": "계정 경험치", "type": "integer" },
                    "characterExp": { "description": "캐릭터 경험치", "type": "integer" }
                }
            }
        },
        "required": [ "id" ]
    }
}

=== lsm1987/DataExporter/docs/sample/assets/sample_complex.json
[
    {
        "id": "daily_stage_1",
        "name": "불의 던전",
        "openTimes": [
            {
                "dayOfWeek": "Monday",
                "startTime": "06:00",
                "endTime": "20:00"
            },
            {
                "dayOfWeek": "Saturday",
                "startTime": "00:00",
                "endTime": "23:00"
            }
        ],
        "rewards": [
            {
                "itemId": 1001,
                "count": 1,
                "condition": {
                    "firstClear": true
                },
                "messages": [
                    {
                        "text": "최초 클리어 보상 획득!",
                        "delay": 0.0
                    },
                    {
                        "text": "영웅 보관함을 확인해주세요.",
                        "delay": 1.5
                    }
                ]
            },
            {
                "itemId": 2001,
                "count": 1,
                "condition": {
                    "timeLimit": 300
                },
                "messages": [
                    {
                        "text": "제한시간 내 클리어 보상 획득!",
                        "delay": 0.0
                    }
                ]
            },
            {
                "itemId": 2001,
                "count": 10
            }
        ],
        "exp": {
            "accountExp": 100,
            "characterExp": 33
        }
    },
    {
        "id": "daily_stage_2",
        "name": "물의 던전",
        "openTimes": [
            {
                "dayOfWeek": "Tuesday",
                "startTime": "06:00",
                "endTime": "20:00"
            },
            {
                "dayOfWeek": "Sunday",
                "startTime": "00:00",
                "endTime": "23:00"
            }
        ],
        "rewards": [
            {
                "itemId": 1002,
                "count": 1,
                "condition": {
                    "firstClear": true
                },
                "messages": [
                    {
                        "text": "최초 클리어 보상 획득!",
                        "delay": 0.0
                    },
                    {
                        "text": "영웅 보관함을 확인해주세요.",
                        "delay": 1.5
                    }
                ]
            },
            {
                "itemId": 2002,
                "count": 1,
                "condition": {
                    "timeLimit": 300
                },
                "messages": [
                    {
                        "text": "제한시간 내 클리어 보상 획득!",
                        "delay": 0.0
                    }
                ]
            },
            {
                "itemId": 2002,
                "count": 10
            }
        ],
        "exp": {
            "accountExp": 100,
            "characterExp": 33
        }
    }
]
